### ISSUE TITLE
Panic makeslice: len out of range

### ISSUE THREAD

**Issue by awnumar** [prologic/bitcask#30]
This happens on the second or third run. On every exit I call Sync, Merge, Close in that order. After the second run the amount of data on disk was still twice what it should be. Then on the merge call before closing:

```
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
github.com/prologic/bitcask/internal/streampb.(*Decoder).Decode(0xc000ef4af0, 0x6a5940, 0xc025221a40, 0x107f, 0x32844, 0x107f)
	/home/awn/go/pkg/mod/github.com/prologic/bitcask@v0.2.3-0.20190726215738-bc782a3083ba/internal/streampb/stream.go:79 +0xc9
github.com/prologic/bitcask/internal.(*Datafile).ReadAt(0xc000155130, 0x32844, 0x107f, 0x7c, 0x32844, 0x107f, 0xc000018001, 0x7fd58f451518, 0x1, 0x10100c000024000, ...)
	/home/awn/go/pkg/mod/github.com/prologic/bitcask@v0.2.3-0.20190726215738-bc782a3083ba/internal/datafile.go:156 +0x147
github.com/prologic/bitcask.(*Bitcask).Get(0xc0000c2000, 0xc000440040, 0x40, 0xc000ef4c40, 0x405a2b, 0xc0000180c0, 0xc000ef4c78, 0xc000018001)
	/home/awn/go/pkg/mod/github.com/prologic/bitcask@v0.2.3-0.20190726215738-bc782a3083ba/bitcask.go:124 +0xa2
github.com/prologic/bitcask.(*Bitcask).Merge.func1(0xc000440040, 0x40, 0x42a901, 0xc02520db00)
	/home/awn/go/pkg/mod/github.com/prologic/bitcask@v0.2.3-0.20190726215738-bc782a3083ba/bitcask.go:341 +0x4b
github.com/prologic/bitcask.(*Bitcask).Fold(0xc0000c2000, 0xc000ef4d40, 0x0, 0x0)
	/home/awn/go/pkg/mod/github.com/prologic/bitcask@v0.2.3-0.20190726215738-bc782a3083ba/bitcask.go:205 +0x8b
github.com/prologic/bitcask.(*Bitcask).Merge(0xc0000c2000, 0x0, 0x0)
	/home/awn/go/pkg/mod/github.com/prologic/bitcask@v0.2.3-0.20190726215738-bc782a3083ba/bitcask.go:340 +0x170
main.main.func1()
	/home/awn/go/src/github.com/awnumar/gravity/main.go:18 +0xa4
main.main()
	/home/awn/go/src/github.com/awnumar/gravity/main.go:85 +0x6b3
exit status 2
```

**Comment by prologic** [comment]
So this is happenning here:

```#!go
// Decode takes a proto.Message and unmarshals the next payload in the
// underlying io.Reader. It returns an EOF when it's done.
func (d *Decoder) Decode(v proto.Message) (int64, error) {
        prefixBuf := make([]byte, prefixSize)

        _, err := io.ReadFull(d.r, prefixBuf)
        if err != nil {
                return 0, err
        }

        n := binary.BigEndian.Uint64(prefixBuf)

        buf := make([]byte, n)

        idx := uint64(0)
        for idx < n {
                m, err := d.r.Read(buf[idx:n])
                if err != nil {
                        return 0, errors.Wrap(translateError(err), "failed reading marshaled data")
                }
                idx += uint64(m)
        }
        return int64(idx + prefixSize), proto.Unmarshal(buf[:n], v)
}
```

Which means `n` is whatthing weird?

**Comment by prologic** [comment]
Might be useful if we can find a small repro case?

**Comment by prologic** [comment]
This [SO Q&A](https://stackoverflow.com/questions/27647737/maximum-length-of-a-slice-in-go) might shed some light here...

**Comment by prologic** [comment]
What's your  `MaxDatafileSize` out of curiosity?

**Comment by prologic** [comment]
And how large are your datafiles before `Merge()`?

**Comment by prologic** [comment]
My train of thought is is this...

> I wonder if there is a situation where `MaxDatafilesize` and large key/value pairs could cause `n` in `streampb.Decode()` to be greater than the default `int` on the platform causing the saftety check in `makeslice()` to panic...

**Comment by prologic** [comment]
Ooooh hold on a second...

```
    if len64 < 0 || int64(len) != len64 || t.elem.size > 0 && uintptr(len) > maxmem/uintptr(t.elem.size) {
```
I wonder if you're hitting `uintptr(len) > maxmem/uintptr(t.elem.size)`?

Again; how large are thee values you're writing?

**Comment by prologic** [comment]
Hmmm this is quite weird; I can't believe you're hitting these limits :/ That check is a safeguard against theoretical maximum memory not available memory _I think_

**Comment by prologic** [comment]
Need your help debugging this :) Since you have a repro case; some logging, extra details to help understand what is actually going on here...

**Comment by awnumar** [comment]
Been trying to write a self-contained repro case but haven't quite got there yet. To answer your questions:

1. Max data file size is default.
2. Data set is around 100MB and the database is around 104MB the first run and 207M the second time.
3. Each key is 32 bytes and each value is around 4kB.

**Comment by prologic** [comment]
Yeah then you shouldn't be hitting what's described in that SO or the safty checks there on `makeslice()` So this mystery has gotten more interesting :)

Let me know if you can come up with a self-contained repro case? Otherwise just sprinkle some logging around in your environment. If you're not hitting any theoryetical maximum limits of `makeslice()` then I smell a bug :)

**Comment by prologic** [comment]
I _think_ I recall borrowing `streampb` from somewhere... The way it works is to stream protobuf messages to/from an `io.Reader/io.Writer` and frame each message with its length.

**Comment by prologic** [comment]
Q: Do  you experience the same panic/bug if you eomit/skip the `Merge()` -- In other wirds; can you successfully `.Get()` that same key that its b0rking on? If so then that _could_ also smell of some racey behavior to do with the `Merge()` I rewrote :/

**Comment by prologic** [comment]
I wonder if I run the test suite through the race detector...

**Comment by prologic** [comment]
> I wonder if I run the test suite through the race detector...

Ahh I do

```
test: build
	@go test -v \
		-cover -coverprofile=coverage.txt -covermode=atomic \
		-coverpkg=$(shell go list) \
		-race \
		.
```

**Comment by prologic** [comment]
The branch I pushed with a modified `TestMerge()` doesn't trigger this

```
$ go test -v -race .
=== RUN   TestAll
=== RUN   TestAll/Open
=== RUN   TestAll/Put
=== RUN   TestAll/Get
=== RUN   TestAll/Len
=== RUN   TestAll/Has
=== RUN   TestAll/Keys
=== RUN   TestAll/Fold
=== RUN   TestAll/Delete
=== RUN   TestAll/Sync
=== RUN   TestAll/Close
--- PASS: TestAll (0.04s)
    --- PASS: TestAll/Open (0.00s)
    --- PASS: TestAll/Put (0.00s)
    --- PASS: TestAll/Get (0.00s)
    --- PASS: TestAll/Len (0.00s)
    --- PASS: TestAll/Has (0.00s)
    --- PASS: TestAll/Keys (0.00s)
    --- PASS: TestAll/Fold (0.00s)
    --- PASS: TestAll/Delete (0.00s)
    --- PASS: TestAll/Sync (0.02s)
    --- PASS: TestAll/Close (0.01s)
=== RUN   TestDeletedKeys
=== RUN   TestDeletedKeys/Setup
=== RUN   TestDeletedKeys/Setup/Open
=== RUN   TestDeletedKeys/Setup/Put
=== RUN   TestDeletedKeys/Setup/Get
=== RUN   TestDeletedKeys/Setup/Delete
=== RUN   TestDeletedKeys/Setup/Sync
=== RUN   TestDeletedKeys/Setup/Close
=== RUN   TestDeletedKeys/Reopen
=== RUN   TestDeletedKeys/Reopen/Open
=== RUN   TestDeletedKeys/Reopen/Get
=== RUN   TestDeletedKeys/Reopen/Close
--- PASS: TestDeletedKeys (0.03s)
    --- PASS: TestDeletedKeys/Setup (0.01s)
        --- PASS: TestDeletedKeys/Setup/Open (0.00s)
        --- PASS: TestDeletedKeys/Setup/Put (0.00s)
        --- PASS: TestDeletedKeys/Setup/Get (0.00s)
        --- PASS: TestDeletedKeys/Setup/Delete (0.00s)
        --- PASS: TestDeletedKeys/Setup/Sync (0.00s)
        --- PASS: TestDeletedKeys/Setup/Close (0.01s)
    --- PASS: TestDeletedKeys/Reopen (0.01s)
        --- PASS: TestDeletedKeys/Reopen/Open (0.00s)
        --- PASS: TestDeletedKeys/Reopen/Get (0.00s)
        --- PASS: TestDeletedKeys/Reopen/Close (0.01s)
=== RUN   TestMaxKeySize
=== RUN   TestMaxKeySize/Open
=== RUN   TestMaxKeySize/Put
--- PASS: TestMaxKeySize (0.00s)
    --- PASS: TestMaxKeySize/Open (0.00s)
    --- PASS: TestMaxKeySize/Put (0.00s)
=== RUN   TestMaxValueSize
=== RUN   TestMaxValueSize/Open
=== RUN   TestMaxValueSize/Put
--- PASS: TestMaxValueSize (0.00s)
    --- PASS: TestMaxValueSize/Open (0.00s)
    --- PASS: TestMaxValueSize/Put (0.00s)
=== RUN   TestStats
=== RUN   TestStats/Setup
=== RUN   TestStats/Setup/Open
=== RUN   TestStats/Setup/Put
=== RUN   TestStats/Setup/Get
=== RUN   TestStats/Setup/Stats
=== RUN   TestStats/Setup/Sync
=== RUN   TestStats/Setup/Close
--- PASS: TestStats (0.02s)
    --- PASS: TestStats/Setup (0.02s)
        --- PASS: TestStats/Setup/Open (0.00s)
        --- PASS: TestStats/Setup/Put (0.00s)
        --- PASS: TestStats/Setup/Get (0.00s)
        --- PASS: TestStats/Setup/Stats (0.00s)
        --- PASS: TestStats/Setup/Sync (0.00s)
        --- PASS: TestStats/Setup/Close (0.01s)
=== RUN   TestMerge
=== RUN   TestMerge/Setup
=== RUN   TestMerge/Setup/Open
=== RUN   TestMerge/Setup/Put
=== RUN   TestMerge/Merge
=== RUN   TestMerge/Merge/Put
=== RUN   TestMerge/Merge/Merge
=== RUN   TestMerge/Merge/Sync
=== RUN   TestMerge/Merge/Close
=== RUN   TestMerge/Verify
=== RUN   TestMerge/Verify/Open
=== RUN   TestMerge/Verify/Get
=== RUN   TestMerge/Verify/Close
--- PASS: TestMerge (0.08s)
    --- PASS: TestMerge/Setup (0.00s)
        --- PASS: TestMerge/Setup/Open (0.00s)
        --- PASS: TestMerge/Setup/Put (0.00s)
    --- PASS: TestMerge/Merge (0.07s)
        --- PASS: TestMerge/Merge/Put (0.04s)
        --- PASS: TestMerge/Merge/Merge (0.02s)
        --- PASS: TestMerge/Merge/Sync (0.00s)
        --- PASS: TestMerge/Merge/Close (0.01s)
    --- PASS: TestMerge/Verify (0.01s)
        --- PASS: TestMerge/Verify/Open (0.00s)
        --- PASS: TestMerge/Verify/Get (0.00s)
        --- PASS: TestMerge/Verify/Close (0.01s)
=== RUN   TestConcurrent
=== RUN   TestConcurrent/Setup
=== RUN   TestConcurrent/Setup/Open
=== RUN   TestConcurrent/Setup/Put
=== RUN   TestConcurrent/Concurrent
=== RUN   TestConcurrent/Concurrent/Put
=== RUN   TestConcurrent/Concurrent/Get
=== RUN   TestConcurrent/Concurrent/Close
--- PASS: TestConcurrent (0.03s)
    --- PASS: TestConcurrent/Setup (0.00s)
        --- PASS: TestConcurrent/Setup/Open (0.00s)
        --- PASS: TestConcurrent/Setup/Put (0.00s)
    --- PASS: TestConcurrent/Concurrent (0.03s)
        --- PASS: TestConcurrent/Concurrent/Put (0.01s)
        --- PASS: TestConcurrent/Concurrent/Get (0.01s)
        --- PASS: TestConcurrent/Concurrent/Close (0.01s)
=== RUN   TestScan
=== RUN   TestScan/Setup
=== RUN   TestScan/Setup/Open
=== RUN   TestScan/Setup/Put
=== RUN   TestScan/Scan
--- PASS: TestScan (0.00s)
    --- PASS: TestScan/Setup (0.00s)
        --- PASS: TestScan/Setup/Open (0.00s)
        --- PASS: TestScan/Setup/Put (0.00s)
    --- PASS: TestScan/Scan (0.00s)
=== RUN   TestLocking
--- PASS: TestLocking (0.01s)
PASS
ok  	github.com/prologic/bitcask	1.246s
```

**Comment by prologic** [comment]
Curious to see what the value of `n` is here in `streampb.Decode()` -- Have you used [delve](https://github.com/go-delve/delve) before? If you run your program under it and it panics you can walk through the stack frames and introspect things.

**Comment by awnumar** [comment]
I cannot recreate the panic when I comment Merge out. I can Get the values back out. Have not used Delve before but it does look interesting.

**Comment by prologic** [comment]
Oh well that's interesting then... That smells like some weird interaction with the new `Merge()` code I wrote

**Comment by prologic** [comment]
@awnumar Were you able to dig any further into this on your end?

**Comment by awnumar** [comment]
Here's a program that reproduces the issue: https://github.com/awnumar/bitcask_panic

Running it a few times triggers the panic for me.

**Comment by awnumar** [comment]
Sometimes it manages to trigger a `fatal error: runtime: out of memory` also. Getting the values sometimes results in `too many files open`.

**Comment by prologic** [comment]
Thanks so much! I'll try to do some more debugging with your sample reproducer tonight! Expect some replies to this thread soon!

Sounds like too that there might actually be some hidden bugs underneath here -- Since you also report "too many open fds".

**Comment by awnumar** [comment]
The too many open fds could be due to bitcask going back and opening the files for reading again. However my file limit is `524288` so it may be opening them multiple times.

**Comment by prologic** [comment]
> so it may be opening them multiple times

Its not suppose to. There is **exactly** one `Datafile` opened in read-only mode per inactive (_rotated out_) data file. It is kept open until the database is `.Close()`'d. Anyway will look into that if it also creeps up.

**Comment by awnumar** [comment]
Added a [commit](https://github.com/awnumar/bitcask_panic/commit/2e2a9d2429834f714bf6877cf4186b3c19077526) that kicks up a bunch more errors.

**Comment by prologic** [comment]
Good news is that it repros for me so that's a start!

```
prologic@Jamess-MacBook
Mon Jul 29 20:03:31
~/tmp/bitcask_panic
 (master) 0
$ ./panic

prologic@Jamess-MacBook
Mon Jul 29 20:03:46
~/tmp/bitcask_panic
 (master) 0
$

prologic@Jamess-MacBook
Mon Jul 29 20:03:46
~/tmp/bitcask_panic
 (master) 0
$ ^Cpanic

prologic@Jamess-MacBook
Mon Jul 29 20:03:51
~/tmp/bitcask_panic
 (master) 0
$

prologic@Jamess-MacBook
Mon Jul 29 20:03:51
~/tmp/bitcask_panic
 (master) 0
$ ls -1
data
go.mod
go.sum
main.go
panic
store

prologic@Jamess-MacBook
Mon Jul 29 20:03:52
~/tmp/bitcask_panic
 (master) 0
$

prologic@Jamess-MacBook
Mon Jul 29 20:03:52
~/tmp/bitcask_panic
 (master) 0
$ ./panic
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
github.com/prologic/bitcask/internal/streampb.(*Decoder).Decode(0xc000163c40, 0x124b320, 0xc01d95e1e0, 0x107f, 0x3bcbc, 0x107f)
	/Users/prologic/Projects/bitcask/internal/streampb/stream.go:79 +0xc9
github.com/prologic/bitcask/internal.(*Datafile).ReadAt(0xc01e862c30, 0x3bcbc, 0x107f, 0xab, 0x3bcbc, 0x107f, 0x1, 0xc000163cd0, 0x1005cf6, 0xc000080480, ...)
	/Users/prologic/Projects/bitcask/internal/datafile.go:156 +0x147
github.com/prologic/bitcask.(*Bitcask).Get(0xc0000a6000, 0xc0040b47c0, 0x40, 0xc000163d90, 0x100557b, 0xc00008c060, 0xc000163dc8, 0x1)
	/Users/prologic/Projects/bitcask/bitcask.go:124 +0xa2
github.com/prologic/bitcask.(*Bitcask).Merge.func1(0xc0040b47c0, 0x40, 0x1, 0x0)
	/Users/prologic/Projects/bitcask/bitcask.go:341 +0x4b
github.com/prologic/bitcask.(*Bitcask).Fold(0xc0000a6000, 0xc000163e90, 0x0, 0x0)
	/Users/prologic/Projects/bitcask/bitcask.go:205 +0x8b
github.com/prologic/bitcask.(*Bitcask).Merge(0xc0000a6000, 0x0, 0x0)
	/Users/prologic/Projects/bitcask/bitcask.go:340 +0x170
main.main()
	/Users/prologic/tmp/bitcask_panic/main.go:40 +0x19e
```

Now e have a hope of finding out  wtf is going ong :)

**Comment by prologic** [comment]
Just for clarify:

- 505 Datafiles
- 1.9M index

```
$ ls -l *.data | wc -l
505
$ ls -lah | grep data -v
total 509M
drwxr-xr-x 509 prologic _lpoperator  16K Jul 29 21:27 .
drwxr-xr-x   9 prologic _lpoperator  288 Jul 29 21:32 ..
-rw-r--r--   1 prologic _lpoperator 1.9M Jul 29 20:03 index
-rw-------   1 prologic _lpoperator    0 Jul 29 20:03 lock
```

**Comment by prologic** [comment]
And some ~509M of data:

```
$ du -b -s .
531952760	.
```

So no big deal here; but I'm finding some interesting things with delve :) I'll share in a moment

**Comment by prologic** [comment]
And you're right it doesn't always crash:

```
$ dlv debug --
Type 'help' for list of commands.
(dlv) c
Process 29536 has exited with status 0
(dlv)
```

So this kind of smells like a data race / corruption

**Comment by prologic** [comment]
And here comes the interesting bits...

**Comment by awnumar** [comment]
> And some ~509M of data

The data set is 100M so that shouldn't be the case.

**Comment by prologic** [comment]
Debug results:

```
$ dlv debug --
Type 'help' for list of commands.
(dlv) c
> [unrecovered-panic] runtime.fatalpanic() /usr/local/Cellar/go/1.12.7/libexec/src/runtime/panic.go:690 (hits goroutine(1):1 total:1) (PC: 0x10303b0)
Warning: debugging optimized function
	runtime.curg._panic.arg: interface {}(string) "runtime error: makeslice: len out of range"
   685:	// fatalpanic implements an unrecoverable panic. It is like fatalthrow, except
   686:	// that if msgs != nil, fatalpanic also prints panic messages and decrements
   687:	// runningPanicDefers once main is blocked from exiting.
   688:	//
   689:	//go:nosplit
=> 690:	func fatalpanic(msgs *_panic) {
   691:		pc := getcallerpc()
   692:		sp := getcallersp()
   693:		gp := getg()
   694:		var docrash bool
   695:		// Switch to the system stack to avoid any stack growth, which
(dlv) up
> [unrecovered-panic] runtime.fatalpanic() /usr/local/Cellar/go/1.12.7/libexec/src/runtime/panic.go:690 (hits goroutine(1):1 total:1) (PC: 0x10303b0)
Warning: debugging optimized function
Frame 1: /usr/local/Cellar/go/1.12.7/libexec/src/runtime/panic.go:565 (PC: 102fde6)
   560:		// Because it is unsafe to call arbitrary user code after freezing
   561:		// the world, we call preprintpanics to invoke all necessary Error
   562:		// and String methods to prepare the panic strings before startpanic.
   563:		preprintpanics(gp._panic)
   564:
=> 565:		fatalpanic(gp._panic) // should not return
   566:		*(*int)(nil) = 0      // not reached
   567:	}
   568:
   569:	// getargp returns the location where the caller
   570:	// writes outgoing function call arguments.
(dlv) up
> [unrecovered-panic] runtime.fatalpanic() /usr/local/Cellar/go/1.12.7/libexec/src/runtime/panic.go:690 (hits goroutine(1):1 total:1) (PC: 0x10303b0)
Warning: debugging optimized function
Frame 2: /usr/local/Cellar/go/1.12.7/libexec/src/runtime/slice.go:27 (PC: 1046189)
    22:		len   int
    23:		cap   int
    24:	}
    25:
    26:	func panicmakeslicelen() {
=>  27:		panic(errorString("makeslice: len out of range"))
    28:	}
    29:
    30:	func panicmakeslicecap() {
    31:		panic(errorString("makeslice: cap out of range"))
    32:	}
(dlv) up
> [unrecovered-panic] runtime.fatalpanic() /usr/local/Cellar/go/1.12.7/libexec/src/runtime/panic.go:690 (hits goroutine(1):1 total:1) (PC: 0x10303b0)
Warning: debugging optimized function
Frame 3: /usr/local/Cellar/go/1.12.7/libexec/src/runtime/slice.go:44 (PC: 104623d)
    39:			// 'cap out of range' is true too, but since the cap is only being
    40:			// supplied implicitly, saying len is clearer.
    41:			// See golang.org/issue/4085.
    42:			mem, overflow := math.MulUintptr(et.size, uintptr(len))
    43:			if overflow || mem > maxAlloc || len < 0 {
=>  44:				panicmakeslicelen()
    45:			}
    46:			panicmakeslicecap()
    47:		}
    48:
    49:		return mallocgc(mem, et, true)
(dlv) up
> [unrecovered-panic] runtime.fatalpanic() /usr/local/Cellar/go/1.12.7/libexec/src/runtime/panic.go:690 (hits goroutine(1):1 total:1) (PC: 0x10303b0)
Warning: debugging optimized function
Frame 4: /Users/prologic/Projects/bitcask/internal/streampb/stream.go:79 (PC: 12179b1)
    74:			return 0, err
    75:		}
    76:
    77:		n := binary.BigEndian.Uint64(prefixBuf)
    78:
=>  79:		buf := make([]byte, n)
    80:
    81:		idx := uint64(0)
    82:		for idx < n {
    83:			m, err := d.r.Read(buf[idx:n])
    84:			if err != nil {
(dlv) p prefixBuf
[]uint8 len: 8, cap: 8, [96,187,10,150,35,0,0,0]
(dlv) p n
6970176488234549248
(dlv) up
> [unrecovered-panic] runtime.fatalpanic() /usr/local/Cellar/go/1.12.7/libexec/src/runtime/panic.go:690 (hits goroutine(1):1 total:1) (PC: 0x10303b0)
Warning: debugging optimized function
Frame 5: /Users/prologic/Projects/bitcask/internal/datafile.go:156 (PC: 1241fcd)
   151:			return
   152:		}
   153:
   154:		buf := bytes.NewBuffer(b)
   155:		dec := streampb.NewDecoder(buf)
=> 156:		_, err = dec.Decode(&e)
   157:		return
   158:	}
   159:
   160:	func (df *Datafile) Write(e pb.Entry) (int64, int64, error) {
   161:		if df.w == nil {
(dlv) up
> [unrecovered-panic] runtime.fatalpanic() /usr/local/Cellar/go/1.12.7/libexec/src/runtime/panic.go:690 (hits goroutine(1):1 total:1) (PC: 0x10303b0)
Warning: debugging optimized function
Frame 6: /Users/prologic/Projects/bitcask/bitcask.go:124 (PC: 1244471)
   119:			df = b.curr
   120:		} else {
   121:			df = b.datafiles[item.FileID]
   122:		}
   123:
=> 124:		e, err := df.ReadAt(item.Offset, item.Size)
   125:		if err != nil {
   126:			return nil, err
   127:		}
   128:
   129:		checksum := crc32.ChecksumIEEE(e.Value)
(dlv) p item
github.com/prologic/bitcask/internal.Item {FileID: 716, Offset: 806569, Size: 4223}
(dlv) up
> [unrecovered-panic] runtime.fatalpanic() /usr/local/Cellar/go/1.12.7/libexec/src/runtime/panic.go:690 (hits goroutine(1):1 total:1) (PC: 0x10303b0)
Warning: debugging optimized function
Frame 7: /Users/prologic/Projects/bitcask/bitcask.go:341 (PC: 1247a03)
   336:
   337:		// Rewrite all key/value pairs into merged database
   338:		// Doing this automatically strips deleted keys and
   339:		// old key/value pairs
   340:		err = b.Fold(func(key string) error {
=> 341:			value, err := b.Get(key)
   342:			if err != nil {
   343:				return err
   344:			}
   345:
   346:			if err := mdb.Put(key, value); err != nil {
(dlv) p key
"f651bb8dbe85d4f92b937ab3d8e7c963b9a99ae4e5874cab3b2913198360a489"
(dlv) up
> [unrecovered-panic] runtime.fatalpanic() /usr/local/Cellar/go/1.12.7/libexec/src/runtime/panic.go:690 (hits goroutine(1):1 total:1) (PC: 0x10303b0)
Warning: debugging optimized function
Frame 8: /Users/prologic/Projects/bitcask/bitcask.go:205 (PC: 1244fc4)
   200:	// Fold iterates over all keys in the database calling the function `f` for
   201:	// each key. If the function returns an error, no further keys are processed
   202:	// and the error returned.
   203:	func (b *Bitcask) Fold(f func(key string) error) error {
   204:		for key := range b.keydir.Keys() {
=> 205:			if err := f(key); err != nil {
   206:				return err
   207:			}
   208:		}
   209:		return nil
   210:	}
(dlv) up
> [unrecovered-panic] runtime.fatalpanic() /usr/local/Cellar/go/1.12.7/libexec/src/runtime/panic.go:690 (hits goroutine(1):1 total:1) (PC: 0x10303b0)
Warning: debugging optimized function
Frame 9: /Users/prologic/Projects/bitcask/bitcask.go:340 (PC: 1246973)
   335:		}
   336:
   337:		// Rewrite all key/value pairs into merged database
   338:		// Doing this automatically strips deleted keys and
   339:		// old key/value pairs
=> 340:		err = b.Fold(func(key string) error {
   341:			value, err := b.Get(key)
   342:			if err != nil {
   343:				return err
   344:			}
   345:
(dlv) up
> [unrecovered-panic] runtime.fatalpanic() /usr/local/Cellar/go/1.12.7/libexec/src/runtime/panic.go:690 (hits goroutine(1):1 total:1) (PC: 0x10303b0)
Warning: debugging optimized function
Frame 10: ./main.go:40 (PC: 1248d2f)
    35:		for val := next(); val != nil; val = next() {
    36:			store.Put(fmt.Sprintf("%x", val[:32]), val[32:])
    37:		}
    38:
    39:		store.Sync()
=>  40:		store.Merge()
    41:		store.Close()
    42:	}
    43:
    44:	func next() []byte {
    45:		if index+4168 > len(data) {
(dlv) up
> [unrecovered-panic] runtime.fatalpanic() /usr/local/Cellar/go/1.12.7/libexec/src/runtime/panic.go:690 (hits goroutine(1):1 total:1) (PC: 0x10303b0)
Warning: debugging optimized function
Frame 11: /usr/local/Cellar/go/1.12.7/libexec/src/runtime/proc.go:200 (PC: 1031c4f)
   195:			// A program compiled with -buildmode=c-archive or c-shared
   196:			// has a main, but it is not executed.
   197:			return
   198:		}
   199:		fn = main_main // make an indirect call, as the linker doesn't know the address of the main package when laying down the runtime
=> 200:		fn()
   201:		if raceenabled {
   202:			racefini()
   203:		}
   204:
   205:		// Make racy client program work: if panicking on
(dlv) exit
```

- Key: `f651bb8dbe85d4f92b937ab3d8e7c963b9a99ae4e5874cab3b2913198360a489`
- For some reason `n` is `6970176488234549248` which is insane
- `prefixBuf` was read in as `[]uint8 len: 8, cap: 8, [96,187,10,150,35,0,0,0]` which is the correct BigEndian encoding for `n` of `6970176488234549248`

If you understand what `prefixBuf` is by looking at how its used in `Encode()` and `Decode()` you'll see that its used as the "framing" of each key/value pair encoded in the datafiles:

```
func (e *Encoder) Encode(msg proto.Message) (int64, error) {
        prefixBuf := make([]byte, prefixSize)

        buf, err := proto.Marshal(msg)
        if err != nil {
                return 0, err
        }
        binary.BigEndian.PutUint64(prefixBuf, uint64(len(buf)))

        if _, err := e.w.Write(prefixBuf); err != nil {
                return 0, errors.Wrap(err, "failed writing length prefix")
        }

        n, err := e.w.Write(buf)
        if err != nil {
                return 0, errors.Wrap(err, "failed writing marshaled data")
        }

        if err = e.w.Flush(); err != nil {
                return 0, errors.Wrap(err, "failed flushing data")
        }

        return int64(n + prefixSize), nil
}
```

There are two possibilities here:

- Either there is a data race and something is getting corrupted
- That key/value was really encoded with that size `prefixBuf` (wut?!)

**Comment by prologic** [comment]
> > And some ~509M of data
> 
> The data set is 100M so that shouldn't be the case.

On you're right! Initially it's ~104M in total disk size of `./store` -- inline with what your dataset is.

But on subsequent runs the data keeps growing and the no. of datafiles keeps growing.

**Comment by prologic** [comment]
Why don't you have a look at the code I wrote for `Merge()` and see if you can spot an obvious bug? :) I'll keep digging...

**Comment by prologic** [comment]
Hold on wait I'm confused :)

Of course if I keep running this program the data will keep  growing right? :)

**Comment by prologic** [comment]
But it **should not** panic by inserting more data :/

**Comment by prologic** [comment]
@awnumar I don't seem to be able to repro with the debug#38 branch and commit 4c971779a44bb3da0cd0a9d2ffab210137109d50

Can you try?

**Comment by prologic** [comment]
Oh nevermind :/ Damnit hutn continues...

**Comment by prologic** [comment]
I think I found the bug

**Comment by prologic** [comment]
```
(dlv) p df
*github.com/prologic/bitcask/internal.Datafile {
	RWMutex: sync.RWMutex {
		w: (*sync.Mutex)(0xc000107720),
		writerSem: 0,
		readerSem: 0,
		readerCount: 0,
		readerWait: 0,},
	id: 105,
	r: *os.File {
		file: *(*os.file)(0xc01d9c5800),},
	ra: *golang.org/x/exp/mmap.ReaderAt {
		data: []uint8 len: 1051506, cap: 1051506, [0,0,0,0,0,0,16,114,8,133,253,232,68,18,64,98,97,49,102,48,53,97,53,52,53,53,99,99,50,56,57,101,48,102,57,57,53,102,102,50,98,57,49,100,51,100,100,97,51,102,102,56,100,53,57,101,53,51,102,100,52,49,52,101,...+1051442 more],},
	w: *os.File nil,
	offset: 1051506,
	dec: *github.com/prologic/bitcask/internal/streampb.Decoder {
		r: io.Reader(*os.File) ...,},
	enc: *github.com/prologic/bitcask/internal/streampb.Encoder {
		w: *(*bufio.Writer)(0xc01d939e40),},}
(dlv) p item
github.com/prologic/bitcask/internal.Item {FileID: 106, Offset: 945931, Size: 4223}
(dlv)
```

Notice the discrepency in `df.id` and `item.FileID`?

**Comment by prologic** [comment]
we're somehow reading the wrong file :/

**Comment by awnumar** [comment]
Oh interesting. Well spotted.

By the way could you try not to use lots of separate issue comments to convey something that could fit within a few? It results in lots of emails on my end :)

**Comment by prologic** [comment]
> Oh interesting. Well spotted. The offset also seems to be different.

Yup looks like we have a weird "off-by-one" bug somewhere. But I'm now having trouble figuring out where :/

> By the way could you try not to use lots of separate issue comments to convey something that could fit within a few? It results in lots of emails on my end :)

Ooops sorry :)

**Comment by prologic** [comment]
Fixed 😎

```
prologic@Jamess-MacBook
Mon Jul 29 23:42:34
~/tmp/bitcask_panic
 (master) 0
$ for i in $(seq 0 10); do rm -rf store/ && ./panic && ./panic; echo "Pass #$i"; done
Pass #0
Pass #1
Pass #2
Pass #3
Pass #4
Pass #5
Pass #6
Pass #7
Pass #8
Pass #9
Pass #10
```

**Comment by prologic** [comment]
@awnumar Now that this bug is confirmed to be fixed; I don't suppose you'd mind un-publishing that `bitcask_panic` repo? Just so it doesn't affect search results in strange ways :)

**Comment by awnumar** [comment]
I already did
