### ISSUE TITLE
Storing encrypted strings

### ISSUE THREAD

**Issue by alexelisenko** [prologic/bitcask#66]
Hi,

I am trying to use bitcask as a storage backend for my application, but I would like the data stored to be encrypted. I have tried doing the following, but I am getting errors. Any help on figuring out if/how this can be done properly would be greatly appreciated.

Error:

```
Opening DB
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x13a2027]

goroutine 1 [running]:
github.com/prologic/bitcask.(*Bitcask).Put(0x0, 0xc00019c000, 0x7, 0x8, 0xc00019a0e0, 0x69, 0x70, 0x0, 0x1481edd)
        /Users/alex/go/src/github.com/prologic/bitcask/bitcask.go:146 +0x37
main.Storage.Write(0x1484631, 0x10, 0x0, 0x1481edd, 0x7, 0x13eb400, 0xc0000a4200, 0xc0000a6101, 0x0, 0x0)
        /Users/alex/Documents/project/desktop-cli/storage.go:105 +0x215
main.main.func1(0xc0000f4f00, 0xc00006b800, 0x0, 0x4)
        /Users/alex/Documents/project/desktop-cli/main.go:67 +0x32e
github.com/spf13/cobra.(*Command).execute(0xc0000f4f00, 0xc00006b7c0, 0x4, 0x4, 0xc0000f4f00, 0xc00006b7c0)
        /Users/alex/go/src/github.com/spf13/cobra/command.go:833 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000f4c80, 0xc0000e9f80, 0x1, 0x1)
        /Users/alex/go/src/github.com/spf13/cobra/command.go:917 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/alex/go/src/github.com/spf13/cobra/command.go:867
main.main()
        /Users/alex/Documents/project/desktop-cli/main.go:188 +0x669
exit status 2
```

My Code:

```
package main

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"encoding/json"
	"fmt"
	"io"

	"github.com/prologic/bitcask"
)

// Storage represents the local database store
type Storage struct {
	dbPath string
	db     *bitcask.Bitcask
}

var _encryptionKey = "someCoolSecret*@&(UI@BJHBH@JBHJB"

func encrypt(data []byte) ([]byte, error) {
	block, bErr := aes.NewCipher([]byte(_encryptionKey))
	if bErr != nil {
		return nil, bErr
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return nil, err
	}
	nonce := make([]byte, gcm.NonceSize())
	if _, err = io.ReadFull(rand.Reader, nonce); err != nil {
		return nil, err
	}
	ciphertext := gcm.Seal(nonce, nonce, data, nil)
	return ciphertext, nil
}

func decrypt(data []byte) ([]byte, error) {
	key := []byte(_encryptionKey)
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, err
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return nil, err
	}
	nonceSize := gcm.NonceSize()
	nonce, ciphertext := data[:nonceSize], data[nonceSize:]
	plaintext, err := gcm.Open(nil, nonce, ciphertext, nil)
	if err != nil {
		return nil, err
	}
	return plaintext, nil
}

// Open sets the db connection on Storage
func (s Storage) Open() error {
	if s.db == nil {
		fmt.Println("Opening DB")
		db, err := bitcask.Open(s.dbPath)
		if err != nil {
			fmt.Printf("Error opening db: %s", err.Error())
			return err
		}
		s.db = db
	}
	return nil
}

// Write saves data to the DB with an encrypted value
func (s Storage) Write(key string, value interface{}, plain bool) error {

	if openErr := s.Open(); openErr != nil {
		return openErr
	}

	//JSON encode the value
	var strVal []byte

	if plain == false {

		jsonValue, jsonErr := json.Marshal(value)

		if jsonErr != nil {
			return jsonErr
		}

		strVal = jsonValue

	} else {

		strVal = []byte(value.(string))

	}

	//Encrypt the value
	encValue, encErr := encrypt(strVal)

	if encErr != nil {
		return encErr
	}

	return s.db.Put([]byte(key), encValue)

}

// Read returns decrypted value from DB
func (s Storage) Read(key string, plain bool) (interface{}, error) {

	if openErr := s.Open(); openErr != nil {
		return nil, openErr
	}

	// read the value from db
	encValue, readErr := s.db.Get([]byte(key))

	if readErr != nil {
		return nil, readErr
	}

	// decrypt value
	strValue, decErr := decrypt(encValue)

	if decErr != nil {
		return nil, decErr
	}

	// if not a plain value json decode
	if plain == false {

		var jsonData map[string]interface{}
		if jsonErr := json.Unmarshal(strValue, &jsonData); jsonErr != nil {
			return nil, jsonErr
		}
		return jsonData, nil
	}

	return strValue, nil

}

```

**Comment by awnumar** [comment]
Use a cleaner encryption package instead of rolling your own: https://godoc.org/golang.org/x/crypto/nacl/secretbox

From your code and the stack trace it looks to me like you did not initialise the database with `Open`.

**Comment by jsign** [comment]
In particular, your `Open` method should use a pointer receiver, not a value receiver: `func (s *Storage) Open() error`

**Comment by alexelisenko** [comment]
Yeah, I just realized that it was failing even unencrypted, it was as you said @jsign needed a pointer receiver.

@awnumar I'll talke a look

Thank you!
